before_script:
  - apt-get -qq update && apt-get -qq install -y cppcheck cmake clang python3-pip libiomp-dev &> log_install
  - python3 --version
  - pip3 install cpplint

stages:
  - coding_style
  - clang_build
  - gnu_build
  - benchmark

coding_style:
  stage: coding_style
  script:
    - python3 build.py lint

clang_build:
  stage: clang_build
  script:
    - python3 build.py build clang
    - python3 build.py test
    - python3 build.py run

gnu_build:
  stage: gnu_build
  script:
    - python3 build.py build g++
    - python3 build.py test
    - python3 build.py run

benchmark:
  stage: benchmark
  script:
    - python3 build.py build
    - python3 build.py benchmark
