before_script:
  - apt-get -qq update && apt-get -qq install -y cppcheck cmake

stages:
  - coding_style
  - build
  - run_application

coding_style:
  stage: coding_style
  script:
    - python scripts/lint.py

build:
  stage: build
  variables:
    GRAPH_PARTITION_BUILD_PATH:  $CI_PROJECT_DIR/build
  artifacts:
    paths:
      - $GRAPH_PARTITION_BUILD_PATH
  script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck -j4 --project=compile_commands.json &> log_cppcheck
    - python ../scripts/static_analysis.py log_cppcheck
    - make -j4

run_application:
  stage: run_application
  variables:
  script:
    - .$GRAPH_PARTITION_BUILD_PATH/modules/application/Graph_Partition
