before_script:
  - apt-get -qq install -y apt-utils &> log_install_apt_utils
  - apt-get -qq update &> log_update
  - apt-get -qq upgrade &> log_upgrade
  - apt-get -qq install -y cppcheck &> log_install_cppcheck
  - apt-get -qq install -y cmake &> log_install_cmake

stages:
  - coding_style
  - build_and_run

coding_style:
  stage: coding_style
  script:
    - python scripts/lint.py $CI_PROJECT_DIR

build_and_run:
  stage: build_and_run
  script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck -j4 --project=compile_commands.json &> log_cppcheck
    - python ../scripts/static_analysis.py log_cppcheck
    - make -j4
    - ./modules/application/Graph_Partition
