before_script:
  - apt-get -qq update && apt-get -qq install -y cppcheck cmake &> log_install

stages:
  - coding_style
  - build
  - tests
  - run

coding_style:
  stage: coding_style
  script:
    - python scripts/lint.py $CI_PROJECT_DIR

build:
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/
  script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck -j4 --project=compile_commands.json &> log_cppcheck
    - python ../scripts/static_analysis.py log_cppcheck
    - make -j4

tests:
  stage: tests
  script:
    - cd build/tests
    - ./Test_Target
  dependencies:
    - build

run:
  stage: run
  script:
    - cd build/modules/application
    - ./Graph_Partition
  dependencies:
    - build
