before_script:
  - apt-get -qq update && apt-get -qq install -y cppcheck cmake

stages:
  - build_and_run

build_and_run:
  stage: build_and_run
  script:
    - python3 scripts/lint.py $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck -j4 --project=compile_commands.json &> log_cppcheck
    - python3 ../scripts/static_analysis.py log_cppcheck
    - make -j4
    - ./modules/application/Graph_Partition
