language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      install: sudo apt-get install libomp*
      script: python build.py build g++
    - os: osx
      osx_image: xcode7.2
      script: python build.py build clang
    - os: windows
      script: python build.py build msvc
