language: cpp

os:
  - linux
  - osx
  - windows

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];   python build.py build gcc;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];     python build.py build clang;
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; python build.py build msvc;
