language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      install:
        - sudo apt-get install libomp* python3-pip
        - sudo pip install --upgrade pip
        - sudo pip install setuptools cpplint
      script:
        - python build.py lint
        - python build.py build g++
        - python build.py test g++
    - os: windows
      script:
        - python build.py build msvc
        - python build.py test msvc
    # - os: osx
    #   osx_image: xcode10.1
    #   script: python build.py build clang
