language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - sudo apt-get install libomp* python3-pip
      script:
        - python build.py build g++
        - python build.py test g++
        - python build.py benchmark g++
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      before_install:
        - sudo apt-get install libiomp*
      script:
        - python build.py build clang
        - python build.py test clang
        - python build.py benchmark clang
    #######################################################
    - os: osx
      osx_image: xcode10.1
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp
      script:
        - python build.py build clang
        - python build.py test clang
        # - python build.py benchmark clang
    #######################################################

install:
  - sudo pip install --upgrade pip
  - sudo pip install setuptools cpplint
