language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      install:
        - sudo apt-get install libomp* python3-pip
        - sudo pip install --upgrade pip
        - sudo pip install setuptools cpplint
      script:
        - python build.py lint
        - python build.py build g++
        - python build.py test g++
        - python build.py benchmark g++
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - sudo apt-get install libiomp-dev
      script:
        - python build.py build clang
        - python build.py test clang
        - python build.py benchmark clang
    #######################################################
    - os: windows
      script:
        - python build.py build msvc
        # - python build.py test msvc
        - python build.py benchmark msvc
    #######################################################
    # - os: osx
    #   osx_image: xcode10.1
    #   script: python build.py build clang
    #######################################################
